### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by 1936268516** [Zergatul/freecam#12]
After the "out-of-body" experience, you can't turn the viewpoint by moving the mouse, you can only see the character turn his head

forge:1.20.1-47-2-30
forge:FreeCam2.0.0

**Comment by Zergatul** [comment]
Delete better3rdperson mod

**Comment by 1936268516** [comment]
> 删除 better3rdperson mod

I don't have better3rdperson installed and am using Epic Fight is that a conflict with this.

**Comment by Zergatul** [comment]
Ok, I may look into this later.

**Comment by aLyinxz** [comment]
Same issue with Timeless and Classics Zero mod
log strings:
```
[Render thread/WARN]: @Redirect conflict. Skipping zergatul.freecam.mixin.json:MixinMouseHandler->@Redirect::onLocalPlayerTurn(Lnet/minecraft/client/player/LocalPlayer;DD)V with priority 1000, already redirected by tacz.mixins.json:client.MouseHandlerMixin->@Redirect::reduceSensitivity(Lnet/minecraft/client/player/LocalPlayer;DD)V with priority 1000
[Render thread/WARN]: The following mods have version differences that were not resolved:
freecam (version 1.2.1+1.20 -> MISSING)
```

**Comment by Zergatul** [comment]
> Same issue with Timeless and Classics Zero mod log strings:
> 
> ```
> [Render thread/WARN]: @Redirect conflict. Skipping zergatul.freecam.mixin.json:MixinMouseHandler->@Redirect::onLocalPlayerTurn(Lnet/minecraft/client/player/LocalPlayer;DD)V with priority 1000, already redirected by tacz.mixins.json:client.MouseHandlerMixin->@Redirect::reduceSensitivity(Lnet/minecraft/client/player/LocalPlayer;DD)V with priority 1000
> [Render thread/WARN]: The following mods have version differences that were not resolved:
> freecam (version 1.2.1+1.20 -> MISSING)
> ```

Thanks for pointing out directly where on the problem
I will check if this is possible to fix

**Comment by Zergatul** [comment]
Try version 2.0.1 for 1.20.1

**Comment by aLyinxz** [comment]
Everything works! Thank you!
