### ISSUE TITLE
Changing worlds while in freecam breaks normal player view

### ISSUE THREAD

**Issue by sndyx** [Zergatul/freecam#15]
If you change worlds while still in freecam mode (for example, typing /hub in a server while in freecam), attempting to turn off freecam afterwards completely breaks the normal Minecraft view.

Forge 1.8.9 (Not tested on others)

Perhaps it should turn off freecam before your world is changed

**Comment by sndyx** [comment]
Seeing as the 1.8.9 branch hasn't been updated in quite some time I apologize if this version is no longer supported

Unsure whether this applies to newer versions of the mod but if that is the case consider the issue void

**Comment by Zergatul** [comment]
Right, 1.8.9 just has basic features. I have no plans to update it.
