### ISSUE TITLE
I cannot change my keybind!!!

### ISSUE THREAD

**Issue by mortayah-official** [Zergatul/freecam#17]
I cannot change my keybind in the .freecam settings, and it is really annoying since i have another client sided mod thats keybind is also f6.

**Comment by Zergatul** [comment]
Dude, if you can't change keybinding, this is not a mod issue

**Comment by Zergatul** [comment]
You change keybinding via game keybinding settings, not mod settings

**Comment by mortayah-official** [comment]
Well, there is no game settings, do you have any idea how to open it??

Igor Budzhak ***@***.***>, 5 Eyl 2024 Per, 01:26 tarihinde
şunu yazdı:

**Comment by mortayah-official** [comment]
alright thanks!!!!

Igor Budzhak ***@***.***>, 5 Eyl 2024 Per, 01:26 tarihinde
şunu yazdı:
