### ISSUE TITLE
Jade compatible

### ISSUE THREAD

**Issue by NeoStarWonV** [Zergatul/freecam#18]
I want to know if you can make the jade showing the item information what the player are facing when player go into Free View pattern

**Comment by Zergatul** [comment]
I don't really want to add mod-specific changes, unless this is very popular mods like sodium. I never used jade by myself.
I can check how hard this change can be, and if it generic enough to benefit compatibility with other mods.

**Comment by Zergatul** [comment]
It is already working fine for me. I can see dropped item information while in freecam with this jade mod. Seems like you are wasting my time...

**Comment by NeoStarWonV** [comment]
Sorry for disturbing you,It did work when I updated Jade into latest version
