### ISSUE TITLE
Night Vision Freecam

### ISSUE THREAD

**Issue by iamshift** [Zergatul/freecam#2]
If possible could you add an option to use night vision while on freecam?

**Comment by Zergatul** [comment]
This is possible (and my cheatutils mod has it), but I am not sure if it should be separate mod. I understand when you want to explore underground caves without night vision emulation (it is usually called full bright) it is not good.
On the other hand if someone wants to use full bright mod separately, it may conflict with full bright in my mod.
What do you think?

**Comment by iamshift** [comment]
Since you have a mod that does this, there's no point on adding it here. I'll just use cheatutils instead of freecam.

**Comment by Zergatul** [comment]
Ok, I still didn't release few features from freecam to cheatutils (freecam targeted block, and fix for speed independent of fps)
