### ISSUE TITLE
Conflicting mod id

### ISSUE THREAD

**Issue by tr7zw** [Zergatul/freecam#5]
Hey there.
This mod uses "freecam" as mod id, which is 1:1 the same as the already released Freecam mod https://www.curseforge.com/minecraft/mc-mods/free-cam https://modrinth.com/mod/freecam. This causes crashes when checking for the mod using ``FabricLoader.getInstance().isModLoaded("freecam")``, and having the wrong one loaded. Related issue: https://github.com/tr7zw/FirstPersonModel/issues/309

**Comment by Zergatul** [comment]
Thanks for the issue, I will look into it.

**Comment by Zergatul** [comment]
Fixed in 1.3.1 fabric
