### ISSUE TITLE
v1.5.0 for 1.19.2?

### ISSUE THREAD

**Issue by zyxkad** [Zergatul/freecam#7]
I saw your update for v1.5.0, added a command `.freecam target 0`
this is a really useful command for afk with auto clicker

but 1.5.0 only work with minecraft 1.19.3, many mods in forge still leave on 1.19.2
can you compile a version for minecraft 1.19.2, thanks

PS: This mod is really good, thanks for your mod :)

**Comment by Zergatul** [comment]
Ok, I will move this changes to 1.19.2 version

**Comment by Zergatul** [comment]
Done

**Comment by zyxkad** [comment]
Thanks!
