### ISSUE TITLE
shadow is gone

### ISSUE THREAD

**Issue by HSSkyBoy** [Zergatul/freecam#9]
In 1.5.0-orge-1.19.3, when freecam is enabled, the character's shadow will disappear
Hope it can be fixed because I really enjoy photography, but having no shadows would seem strange

**Comment by HSSkyBoy** [comment]
Sorry 
is 1.1.8-forge-1.19.3

**Comment by Zergatul** [comment]
Was it working before? In which version? Maybe you installed additional mods?
